/*global systemDictionary:true */
'use strict';

const dictionary = {
	'linuxcontrol adapter settings': {
		'en': 'Adapter settings for linuxcontrol',
		'de': 'Adaptereinstellungen für linuxcontrol',
		'ru': 'Настройки адаптера для linuxcontrol',
		'pt': 'Configurações do adaptador para linuxcontrol',
		'nl': 'Adapterinstellingen voor linuxcontrol',
		'fr': "Paramètres d'adaptateur pour linuxcontrol",
		'it': "Impostazioni dell'adattatore per linuxcontrol",
		'es': 'Ajustes del adaptador para linuxcontrol',
		'pl': 'Ustawienia adaptera dla linuxcontrol',
		'zh-cn': 'linuxcontrol'
	},
	"pollingInterval": {
		"en": "polling interval in minutes",
		"de": "Abfrageintervall in Minuten",
		"ru": "интервал опроса в минутах",
		"pt": "intervalo de pesquisa em minutos",
		"nl": "polling-interval in minuten",
		"fr": "intervalle d'interrogation en minutes",
		"it": "intervallo di polling in minuti",
		"es": "intervalo de sondeo en minutos",
		"pl": "interwał sondowania w minutach",
		"zh-cn": "轮询间隔（分钟）"
	},
	"Name": {
		"en": "datapoint id",
		"de": "Datenpunkt-ID",
		"ru": "Datapoint ID",
		"pt": "ID do ponto de dados",
		"nl": "datapunt id",
		"fr": "identifiant de point de données",
		"it": "ID punto dati",
		"es": "ID de punto de datos",
		"pl": "identyfikator punktu danych",
		"zh-cn": "数据点ID"
	},
	"IP": {
		"en": "IP",
		"de": "IP",
		"ru": "IP",
		"pt": "IP",
		"nl": "IK P",
		"fr": "IP",
		"it": "IP",
		"es": "IP",
		"pl": "IP",
		"zh-cn": "知识产权"
	},
	"Port": {
		"en": "Port",
		"de": "Port",
		"ru": "порт",
		"pt": "Porta",
		"nl": "Haven",
		"fr": "Port",
		"it": "Porta",
		"es": "Puerto",
		"pl": "Port",
		"zh-cn": "港口"
	},
	"User": {
		"en": "User",
		"de": "Benutzer",
		"ru": "пользователь",
		"pt": "Do utilizador",
		"nl": "Gebruiker",
		"fr": "Utilisateur",
		"it": "Utente",
		"es": "Usuario",
		"pl": "Użytkownik",
		"zh-cn": "用户"
	},
	"Password": {
		"en": "Password",
		"de": "Passwort",
		"ru": "пароль",
		"pt": "Senha",
		"nl": "Wachtwoord",
		"fr": "Mot de passe",
		"it": "Parola d'ordine",
		"es": "Contraseña",
		"pl": "Hasło",
		"zh-cn": "密码"
	},
	"Folders": {
		"en": "Folders",
		"de": "Ordner",
		"ru": "Папки",
		"pt": "Pastas",
		"nl": "Mappen",
		"fr": "Dossiers",
		"it": "Cartelle",
		"es": "Carpetas",
		"pl": "Lornetka składana",
		"zh-cn": "资料夹"
	},
	"RSA Key": {
		"en": "RSA Key (path and filename)",
		"de": "RSA-Schlüssel (Pfad und Dateiname)",
		"ru": "Ключ RSA (путь и имя файла)",
		"pt": "Chave RSA (caminho e nome do arquivo)",
		"nl": "RSA-sleutel (pad en bestandsnaam)",
		"fr": "Clé RSA (chemin et nom de fichier)",
		"it": "Chiave RSA (percorso e nome file)",
		"es": "Clave RSA (ruta y nombre de archivo)",
		"pl": "Klucz RSA (ścieżka i nazwa pliku)",
		"zh-cn": "RSA密钥（路径和文件名）"
	},
	"distribution_name": {
		"en": "name of distribution",
		"de": "Name der Distribution",
		"ru": "название распространения",
		"pt": "nome da distribuição",
		"nl": "naam van distributie",
		"fr": "nom de la distribution",
		"it": "nome della distribuzione",
		"es": "nombre de distribución",
		"pl": "nazwa dystrybucji",
		"zh-cn": "发行名称"
	},
	"distribution_fullname": {
		"en": "fullname with version",
		"de": "vollständiger Name mit Version",
		"ru": "полное имя с версией",
		"pt": "nome completo com versão",
		"nl": "volledige naam met versie",
		"fr": "nom complet avec version",
		"it": "nome completo con versione",
		"es": "nombre completo con versión",
		"pl": "pełna nazwa z wersją",
		"zh-cn": "带有版本的全名"
	},
	"distribution_codename": {
		"en": "codename",
		"de": "Code Name",
		"ru": "кодовое имя",
		"pt": "nome de código",
		"nl": "codenaam",
		"fr": "nom de code",
		"it": "nome in codice",
		"es": "nombre clave",
		"pl": "kryptonim",
		"zh-cn": "代码名称"
	},
	"distribution_version": {
		"en": "version",
		"de": "Version",
		"ru": "версия",
		"pt": "versão",
		"nl": "versie",
		"fr": "version",
		"it": "versione",
		"es": "versión",
		"pl": "wersja",
		"zh-cn": "版"
	},
	"newPackages": {
		"en": "new packages",
		"de": "neue Pakete",
		"ru": "новые пакеты",
		"pt": "novos pacotes",
		"nl": "nieuwe pakketten",
		"fr": "nouveaux packages",
		"it": "nuovi pacchetti",
		"es": "nuevos paquetes",
		"pl": "nowe pakiety",
		"zh-cn": "新包装"
	},
	"upgradable": {
		"en": "upgradable",
		"de": "aktualisierbar",
		"ru": "обновляемое",
		"pt": "atualizável",
		"nl": "upgradebaar",
		"fr": "évolutif",
		"it": "aggiornabile",
		"es": "actualizable",
		"pl": "z możliwością aktualizacji",
		"zh-cn": "可升级的"
	},
	"packages": {
		"en": "packages",
		"de": "Pakete",
		"ru": "пакеты",
		"pt": "pacotes",
		"nl": "pakketjes",
		"fr": "paquets",
		"it": "pacchi",
		"es": "paquetes",
		"pl": "paczki",
		"zh-cn": "包装"
	},
	"newPackagesList": {
		"en": "new packages listed",
		"de": "neue Pakete aufgelistet",
		"ru": "новые пакеты в списке",
		"pt": "novos pacotes listados",
		"nl": "nieuwe pakketten vermeld",
		"fr": "nouveaux packages répertoriés",
		"it": "nuovi pacchetti elencati",
		"es": "nuevos paquetes listados",
		"pl": "wymienione nowe pakiety",
		"zh-cn": "列出了新包装"
	},
	"aptUpdate": {
		"en": "refresh packages lists",
		"de": "Paketlisten aktualisieren",
		"ru": "обновить списки пакетов",
		"pt": "atualizar listas de pacotes",
		"nl": "pakketlijsten vernieuwen",
		"fr": "actualiser les listes de packages",
		"it": "aggiorna gli elenchi dei pacchetti",
		"es": "actualizar listas de paquetes",
		"pl": "Odśwież listy pakietów",
		"zh-cn": "刷新软件包列表"
	},
	"aptUpgrade": {
		"en": "perform upgrade",
		"de": "Upgrade durchführen",
		"ru": "выполнить обновление",
		"pt": "realizar atualização",
		"nl": "upgrade uitvoeren",
		"fr": "effectuer une mise à niveau",
		"it": "eseguire l'aggiornamento",
		"es": "realizar actualización",
		"pl": "wykonać aktualizację",
		"zh-cn": "执行升级"
	},
	"controlResponse": {
		"en": "response of the executed command",
		"de": "Antwort des ausgeführten Befehls",
		"ru": "ответ выполненной команды",
		"pt": "resposta do comando executado",
		"nl": "reactie van het uitgevoerde commando",
		"fr": "réponse de la commande exécutée",
		"it": "risposta del comando eseguito",
		"es": "respuesta del comando ejecutado",
		"pl": "odpowiedź wykonanego polecenia",
		"zh-cn": "执行命令的响应"
	},
	"lastUpdate": {
		"en": "last update",
		"de": "letztes Update",
		"ru": "последнее обновление",
		"pt": "última atualização",
		"nl": "laatste update",
		"fr": "dernière mise à jour",
		"it": "ultimo aggiornamento",
		"es": "última actualización",
		"pl": "Ostatnia aktualizacja",
		"zh-cn": "最后更新"
	},
	"general": {
		"en": "general",
		"de": "Allgemein",
		"ru": "Общее",
		"pt": "geral",
		"nl": "algemeen",
		"fr": "général",
		"it": "generale",
		"es": "general",
		"pl": "generał",
		"zh-cn": "一般"
	},
	"datapoints": {
		"en": "datapoints",
		"de": "Datenpunkte",
		"ru": "точки данных",
		"pt": "Os pontos de dados",
		"nl": "data punten",
		"fr": "points de données",
		"it": "datapoints",
		"es": "puntos de datos",
		"pl": "punkty danych",
		"zh-cn": "数据点"
	},
	"expertsettings": {
		"en": "expert settings",
		"de": "Experteneinstellungen",
		"ru": "экспертные настройки",
		"pt": "configurações de especialistas",
		"nl": "deskundige instellingen",
		"fr": "réglages experts",
		"it": "impostazioni di esperti",
		"es": "ajustes expertos",
		"pl": "ustawienia ekspertów",
		"zh-cn": "专家设置"
	},
	"enableExpertSettings": {
		"en": "expert settings enable",
		"de": "Experteneinstellungen aktivieren",
		"ru": "экспертные настройки позволяют",
		"pt": "configurações especializadas permitem",
		"nl": "deskundige instellingen inschakelen",
		"fr": "les paramètres experts permettent",
		"it": "abilitazione impostazioni esperte",
		"es": "ajustes expertos habilitados",
		"pl": "włączenie ustawień eksperckich",
		"zh-cn": "专家设置启用"
	},
	"Host configuration table": {
		"en": "Host configuration table",
		"de": "Host Konfigurationstabelle",
		"ru": "Таблица конфигурации хоста",
		"pt": "Tabela de configuração do host",
		"nl": "Configuratietabel van host",
		"fr": "Table de configuration d'hôte",
		"it": "Tabella di configurazione dell'host",
		"es": "Tabla de configuración de host",
		"pl": "Tabela konfiguracji hosta",
		"zh-cn": "主机配置表"
	},
	"restart": {
		"en": "restart",
		"de": "neu starten",
		"ru": "запустить снова",
		"pt": "reiniciar",
		"nl": "herstarten",
		"fr": "redémarrer",
		"it": "ricomincia",
		"es": "reiniciar",
		"pl": "uruchom ponownie",
		"zh-cn": "重新开始"
	},
	"shutdown": {
		"en": "shutdown",
		"de": "Herunterfahren",
		"ru": "неисправность",
		"pt": "desligar",
		"nl": "afsluiten",
		"fr": "fermer",
		"it": "spegnimento",
		"es": "apagar",
		"pl": "zamknąć",
		"zh-cn": "关掉"
	},
	"whitelistServices": {
		"en": "only creating datapoints for the following services (empty = disabled)",
		"de": "Datenpunkte nur für die folgenden Dienste erstellen (leer = deaktiviert)",
		"ru": "создание только точек данных для следующих сервисов (пусто = отключено)",
		"pt": "apenas criando pontos de dados para os seguintes serviços (vazio = desativado)",
		"nl": "alleen datapunten maken voor de volgende services (leeg = uitgeschakeld)",
		"fr": "création de points de données uniquement pour les services suivants (vide = désactivé)",
		"it": "creando solo punti dati per i seguenti servizi (vuoto = disabilitato)",
		"es": "solo creando puntos de datos para los siguientes servicios (vacío = deshabilitado)",
		"pl": "tylko tworzenie punktów danych dla następujących usług (pusty = wyłączony)",
		"zh-cn": "仅为以下服务创建数据点（空=禁用）"
	},
	"root_control": {
		"en": "Remote control of your Linux distribution",
		"de": "Fernsteuerung deiner Linux-Distribution",
		"ru": "Удаленное управление вашим дистрибутивом Linux",
		"pt": "Controle remoto da sua distribuição Linux",
		"nl": "Afstandsbediening van uw Linux-distributie",
		"fr": "Contrôle à distance de votre distribution Linux",
		"it": "Controllo remoto della tua distribuzione Linux",
		"es": "Control remoto de su distribución de Linux",
		"pl": "Zdalna kontrola dystrybucji Linuksa",
		"zh-cn": "远程控制Linux发行版"
	},
	"root_distribution": {
		"en": "Information about your Linux distribution",
		"de": "Informationen über deine Linux-Distribution",
		"ru": "Информация о вашем дистрибутиве Linux",
		"pt": "Informações sobre sua distribuição Linux",
		"nl": "Informatie over uw Linux-distributie",
		"fr": "Informations sur votre distribution Linux",
		"it": "Informazioni sulla tua distribuzione Linux",
		"es": "Información sobre su distribución de Linux",
		"pl": "Informacje o twojej dystrybucji Linuksa",
		"zh-cn": "有关Linux发行版的信息"
	},
	"root_updates": {
		"en": "Information about updates",
		"de": "Informationen zu Updates",
		"ru": "Информация об обновлениях",
		"pt": "Informações sobre atualizações",
		"nl": "Informatie over updates",
		"fr": "Informations sur les mises à jour",
		"it": "Informazioni sugli aggiornamenti",
		"es": "Información sobre actualizaciones",
		"pl": "Informacje o aktualizacjach",
		"zh-cn": "有关更新的信息"
	},
	"root_services": {
		"en": "Information and remote control of services",
		"de": "Information und Fernsteuerung von Diensten",
		"ru": "Информационное и дистанционное управление услугами",
		"pt": "Informações e controle remoto de serviços",
		"nl": "Informatie en bediening op afstand van diensten",
		"fr": "Information et contrôle à distance des services",
		"it": "Informazioni e controllo remoto dei servizi",
		"es": "Información y control remoto de servicios.",
		"pl": "Informacje i zdalna kontrola usług",
		"zh-cn": "信息和服务的远程控制"
	},
	"root_needrestart": {
		"en": "Information if a reboot is necessary (package 'needrestart' must be installed)",
		"de": "Informationen ob ein Neustart erforderlich ist (Paket 'needrestart' muss installiert sein)",
		"ru": "Информация о необходимости перезагрузки (должен быть установлен пакет needrestart)",
		"pt": "Informações se uma reinicialização for necessária (o pacote 'needrestart' deve ser instalado)",
		"nl": "Informatie als een herstart nodig is (pakket 'needrestart' moet geïnstalleerd zijn)",
		"fr": "Information si un redémarrage est nécessaire (le package 'needrestart' doit être installé)",
		"it": "Informazioni se è necessario un riavvio (è necessario installare il pacchetto 'needrestart')",
		"es": "Información si es necesario reiniciar (se debe instalar el paquete 'needrestart')",
		"pl": "Informacja, czy konieczne jest ponowne uruchomienie komputera (należy zainstalować pakiet „needrestart”)",
		"zh-cn": "如果需要重新启动的信息（必须安装软件包“ needrestart”）"
	},
	"description": {
		"en": "description of service ",
		"de": "Beschreibung des Dienstes",
		"ru": "описание услуги",
		"pt": "Descrição do serviço",
		"nl": "beschrijving van de dienst",
		"fr": "description du service",
		"it": "descrizione del servizio",
		"es": "descripción del Servicio",
		"pl": "opis usługi",
		"zh-cn": "服务说明"
	},
	"load": {
		"en": "service loaded",
		"de": "Dienst geladen",
		"ru": "сервис загружен",
		"pt": "serviço carregado",
		"nl": "service geladen",
		"fr": "service chargé",
		"it": "servizio caricato",
		"es": "servicio cargado",
		"pl": "usługa załadowana",
		"zh-cn": "服务加载"
	},
	"active": {
		"en": "service active",
		"de": "Dienst aktiv",
		"ru": "служба активна",
		"pt": "serviço ativo",
		"nl": "dienst actief",
		"fr": "service actif",
		"it": "servizio attivo",
		"es": "servicio activo",
		"pl": "usługa aktywna",
		"zh-cn": "服务活跃"
	},
	"running": {
		"en": "service running",
		"de": "Dienst läuft",
		"ru": "служба работает",
		"pt": "serviço em execução",
		"nl": "service loopt",
		"fr": "service en cours d'exécution",
		"it": "servizio in esecuzione",
		"es": "servicio en ejecución",
		"pl": "usługa działa",
		"zh-cn": "服务运行"
	},
	"restartService": {
		"en": "restart service ",
		"de": "Dienst neu starten",
		"ru": "перезапустить службу",
		"pt": "reiniciar o serviço",
		"nl": "herstart service",
		"fr": "redémarrer le service",
		"it": "riavvia il servizio",
		"es": "reiniciar servicio",
		"pl": "uruchom ponownie usługę",
		"zh-cn": "重新启动服务"
	},
	"stopService": {
		"en": "stop service ",
		"de": "Dienst anhalten",
		"ru": "остановить сервис",
		"pt": "parar serviço",
		"nl": "stop service",
		"fr": "aire d'autoroute",
		"it": "interrompere il servizio",
		"es": "parada de servicio",
		"pl": "zatrzymać usługę",
		"zh-cn": "停止服务"
	},
	"startService": {
		"en": "start service ",
		"de": "Dienst starten",
		"ru": "начать обслуживание",
		"pt": "Começar serviço",
		"nl": "start dienst",
		"fr": "démarrer le service",
		"it": "avviare il servizio",
		"es": "Empieza el servicio",
		"pl": "uruchomić usługę",
		"zh-cn": "开始服务"
	},
	"needrestart": {
		"en": "restart is needed",
		"de": "Neustart ist erforderlich",
		"ru": "требуется перезагрузка",
		"pt": "é necessário reiniciar",
		"nl": "herstart is nodig",
		"fr": "le redémarrage est nécessaire",
		"it": "è necessario il riavvio",
		"es": "reiniciar es necesario",
		"pl": "konieczne jest ponowne uruchomienie",
		"zh-cn": "需要重启"
	},
	"needRestartServices": {
		"en": "count of services that need a restart",
		"de": "Anzahl der Dienste, die neu gestartet werden müssen",
		"ru": "количество служб, требующих перезапуска",
		"pt": "contagem de serviços que precisam de reinicialização",
		"nl": "aantal services dat opnieuw moet worden opgestart",
		"fr": "nombre de services nécessitant un redémarrage",
		"it": "conteggio dei servizi che richiedono un riavvio",
		"es": "recuento de servicios que necesitan reiniciar",
		"pl": "liczba usług wymagających ponownego uruchomienia",
		"zh-cn": "需要重启的服务数量"
	},
	"needRestartContainers": {
		"en": "count of containers that need a restart",
		"de": "Anzahl der Container, die neu gestartet werden müssen",
		"ru": "количество контейнеров, которые требуют перезагрузки",
		"pt": "contagem de contêineres que precisam de reinicialização",
		"nl": "aantal containers dat opnieuw moet worden opgestart",
		"fr": "nombre de conteneurs nécessitant un redémarrage",
		"it": "conteggio dei contenitori che richiedono un riavvio",
		"es": "recuento de contenedores que necesitan reiniciar",
		"pl": "liczba kontenerów wymagających ponownego uruchomienia",
		"zh-cn": "需要重启的容器数量"
	},
	"needRestartSessions": {
		"en": "count of sessions that need a restart",
		"de": "Anzahl der Sitzungen, die neu gestartet werden müssen",
		"ru": "количество сеансов, требующих перезапуска",
		"pt": "contagem de sessões que precisam ser reiniciadas",
		"nl": "aantal sessies dat opnieuw moet worden opgestart",
		"fr": "nombre de sessions nécessitant un redémarrage",
		"it": "conteggio delle sessioni che richiedono un riavvio",
		"es": "recuento de sesiones que necesitan reiniciar",
		"pl": "liczba sesji wymagających ponownego uruchomienia",
		"zh-cn": "需要重启的会话数"
	},
	"AddService": {
		"en": "add service",
		"de": "Dienst hinzufügen",
		"ru": "добавить сервис",
		"pt": "adicionar serviço",
		"nl": "service toevoegen",
		"fr": "ajouter un service",
		"it": "aggiungi servizio",
		"es": "agregar servicio",
		"pl": "dodaj usługę",
		"zh-cn": "添加服务"
	},
	"Table to configure folders to display their size as data points": {
		"en": "Table to configure folders to display their size as data points",
		"de": "Tabelle zum Konfigurieren von Ordnern, um deren Größe als Datenpunkte anzuzeigen",
		"ru": "Таблица для настройки папок для отображения их размера в виде точек данных",
		"pt": "Tabela para configurar pastas para exibir seu tamanho como pontos de dados",
		"nl": "Tabel om mappen te configureren om hun grootte als gegevenspunten weer te geven",
		"fr": "Tableau pour configurer les dossiers pour afficher leur taille en tant que points de données",
		"it": "Tabella per configurare le cartelle in modo da visualizzarne le dimensioni come punti dati",
		"es": "Tabla para configurar carpetas para mostrar su tamaño como puntos de datos",
		"pl": "Tabela konfiguracji folderów w celu wyświetlania ich rozmiaru jako punktów danych",
		"zh-cn": "用于配置文件夹以将其大小显示为数据点的表"
	},
	"folderSize": {
		"en": "size of folder",
		"de": "Größe des Ordners",
		"ru": "размер папки",
		"pt": "tamanho da pasta",
		"nl": "grootte van de map",
		"fr": "taille du dossier",
		"it": "dimensione della cartella",
		"es": "tamaño de carpeta",
		"pl": "rozmiar folderu",
		"zh-cn": "资料夹大小"
	},
	"Digits": {
		"en": "decimal places",
		"de": "Kommastellen",
		"ru": "десятичные знаки",
		"pt": "casas decimais",
		"nl": "decimalen",
		"fr": "décimales",
		"it": "decimali",
		"es": "lugares decimales",
		"pl": "miejsca dziesiętne",
		"zh-cn": "小数位"
	},
	"Path": {
		"en": "Path",
		"de": "Pfad",
		"ru": "Дорожка",
		"pt": "Caminho",
		"nl": "Pad",
		"fr": "Chemin",
		"it": "Sentiero",
		"es": "Camino",
		"pl": "Ścieżka",
		"zh-cn": "路径"
	},
	"Unit": {
		"en": "Unit",
		"de": "Einheit",
		"ru": "Единица измерения",
		"pt": "Unidade",
		"nl": "Eenheid",
		"fr": "Unité",
		"it": "Unità",
		"es": "Unidad",
		"pl": "Jednostka",
		"zh-cn": "单元"
	},
	"folders": {
		"en": "folders",
		"de": "Ordner",
		"ru": "папки",
		"pt": "pastas",
		"nl": "mappen",
		"fr": "Dossiers",
		"it": "cartelle",
		"es": "carpetas",
		"pl": "lornetka składana",
		"zh-cn": "资料夹"
	},
	"timeout": {
		"en": "timeout",
		"de": "Timeout",
		"ru": "Тайм-аут",
		"pt": "tempo esgotado",
		"nl": "time-out",
		"fr": "temps libre",
		"it": "tempo scaduto",
		"es": "se acabó el tiempo",
		"pl": "koniec czasu",
		"zh-cn": "超时"
	},
	"Table to configure your own commands": {
		"en": "Table to configure your own commands",
		"de": "Tabelle zum Konfigurieren deiner eigenen Befehle",
		"ru": "Таблица для настройки ваших собственных команд",
		"pt": "Tabela para configurar seus próprios comandos",
		"nl": "Tabel om uw eigen commando's te configureren",
		"fr": "Tableau pour configurer vos propres commandes",
		"it": "Tabella per configurare i tuoi comandi",
		"es": "Tabla para configurar tus propios comandos",
		"pl": "Tabela do konfiguracji własnych poleceń",
		"zh-cn": "该表配置您自己的命令"
	}

};

try {
	// @ts-ignore
	systemDictionary = dictionary;
} catch (ignore) { }

try {
	module.exports = dictionary;
} catch (ignore) { }