/*global systemDictionary:true */
'use strict';

const dictionary = {
	'linuxcontrol adapter settings': {
		'en': 'Adapter settings for linuxcontrol',
		'de': 'Adaptereinstellungen für linuxcontrol',
		'ru': 'Настройки адаптера для linuxcontrol',
		'pt': 'Configurações do adaptador para linuxcontrol',
		'nl': 'Adapterinstellingen voor linuxcontrol',
		'fr': "Paramètres d'adaptateur pour linuxcontrol",
		'it': "Impostazioni dell'adattatore per linuxcontrol",
		'es': 'Ajustes del adaptador para linuxcontrol',
		'pl': 'Ustawienia adaptera dla linuxcontrol',
		'zh-cn': 'linuxcontrol'
	},
	"Controlling Linux devices and get information about your system": {
		"en": "Controlling Linux devices and get information about your system",
		"de": "Informationen und Steuerung deiner Linux Geräte",
		"ru": "Управление устройствами Linux и получение информации о вашей системе",
		"pt": "Controlar dispositivos Linux e obter informações sobre seu sistema",
		"nl": "Linux-apparaten besturen en informatie over uw systeem krijgen",
		"fr": "Contrôler les périphériques Linux et obtenir des informations sur votre système",
		"it": "Controllare i dispositivi Linux e ottenere informazioni sul sistema",
		"es": "Controlar dispositivos Linux y obtener información sobre su sistema",
		"pl": "Sterowanie urządzeniami z systemem Linux i uzyskiwanie informacji o systemie",
		"zh-cn": "控制Linux设备并获取有关系统的信息"
	},
	"pollingInterval": {
		"en": "polling interval (minutes)",
		"de": "Abfrageintervall (Minuten)",
		"ru": "интервал опроса (минуты)",
		"pt": "intervalo de pesquisa (minutos)",
		"nl": "polling interval (minuten)",
		"fr": "intervalle d'interrogation (minutes)",
		"it": "intervallo di polling (minuti)",
		"es": "intervalo de sondeo (minutos)",
		"pl": "interwał odpytywania (minuty)",
		"zh-cn": "轮询间隔（分钟）"
	},
	"Name": {
		"en": "datapoint id",
		"de": "Datenpunkt-ID",
		"ru": "Datapoint ID",
		"pt": "ID do ponto de dados",
		"nl": "datapunt id",
		"fr": "identifiant de point de données",
		"it": "ID punto dati",
		"es": "ID de punto de datos",
		"pl": "identyfikator punktu danych",
		"zh-cn": "数据点ID"
	},
	"IP": {
		"en": "IP",
		"de": "IP",
		"ru": "IP",
		"pt": "IP",
		"nl": "IK P",
		"fr": "IP",
		"it": "IP",
		"es": "IP",
		"pl": "IP",
		"zh-cn": "知识产权"
	},
	"Port": {
		"en": "Port",
		"de": "Port",
		"ru": "порт",
		"pt": "Porta",
		"nl": "Haven",
		"fr": "Port",
		"it": "Porta",
		"es": "Puerto",
		"pl": "Port",
		"zh-cn": "港口"
	},
	"User": {
		"en": "User",
		"de": "Benutzer",
		"ru": "пользователь",
		"pt": "Do utilizador",
		"nl": "Gebruiker",
		"fr": "Utilisateur",
		"it": "Utente",
		"es": "Usuario",
		"pl": "Użytkownik",
		"zh-cn": "用户"
	},
	"Password": {
		"en": "Password / Passphrase",
		"de": "Passwort / Passphrase",
		"ru": "Пароль / Пароль",
		"pt": "Senha / Senha",
		"nl": "Wachtwoord / wachtwoordzin",
		"fr": "Mot de passe / phrase de passe",
		"it": "Password / Passphrase",
		"es": "Contraseña / Frase de contraseña",
		"pl": "Hasło / hasło",
		"zh-cn": "密码/密码"
	},
	"Folders": {
		"en": "Folders",
		"de": "Ordner",
		"ru": "Папки",
		"pt": "Pastas",
		"nl": "Mappen",
		"fr": "Dossiers",
		"it": "Cartelle",
		"es": "Carpetas",
		"pl": "Lornetka składana",
		"zh-cn": "资料夹"
	},
	"RSA Key": {
		"en": "RSA Key (path and filename)",
		"de": "RSA-Schlüssel (Pfad und Dateiname)",
		"ru": "Ключ RSA (путь и имя файла)",
		"pt": "Chave RSA (caminho e nome do arquivo)",
		"nl": "RSA-sleutel (pad en bestandsnaam)",
		"fr": "Clé RSA (chemin et nom de fichier)",
		"it": "Chiave RSA (percorso e nome file)",
		"es": "Clave RSA (ruta y nombre de archivo)",
		"pl": "Klucz RSA (ścieżka i nazwa pliku)",
		"zh-cn": "RSA密钥（路径和文件名）"
	},
	"distribution_name": {
		"en": "name of distribution",
		"de": "Name der Distribution",
		"ru": "название распространения",
		"pt": "nome da distribuição",
		"nl": "naam van distributie",
		"fr": "nom de la distribution",
		"it": "nome della distribuzione",
		"es": "nombre de distribución",
		"pl": "nazwa dystrybucji",
		"zh-cn": "发行名称"
	},
	"distribution_fullname": {
		"en": "fullname with version",
		"de": "vollständiger Name mit Version",
		"ru": "полное имя с версией",
		"pt": "nome completo com versão",
		"nl": "volledige naam met versie",
		"fr": "nom complet avec version",
		"it": "nome completo con versione",
		"es": "nombre completo con versión",
		"pl": "pełna nazwa z wersją",
		"zh-cn": "带有版本的全名"
	},
	"distribution_codename": {
		"en": "codename",
		"de": "Code Name",
		"ru": "кодовое имя",
		"pt": "nome de código",
		"nl": "codenaam",
		"fr": "nom de code",
		"it": "nome in codice",
		"es": "nombre clave",
		"pl": "kryptonim",
		"zh-cn": "代码名称"
	},
	"distribution_version": {
		"en": "version",
		"de": "Version",
		"ru": "версия",
		"pt": "versão",
		"nl": "versie",
		"fr": "version",
		"it": "versione",
		"es": "versión",
		"pl": "wersja",
		"zh-cn": "版"
	},
	"newPackages": {
		"en": "new packages",
		"de": "neue Pakete",
		"ru": "новые пакеты",
		"pt": "novos pacotes",
		"nl": "nieuwe pakketten",
		"fr": "nouveaux packages",
		"it": "nuovi pacchetti",
		"es": "nuevos paquetes",
		"pl": "nowe pakiety",
		"zh-cn": "新包装"
	},
	"upgradable": {
		"en": "upgradable",
		"de": "aktualisierbar",
		"ru": "обновляемое",
		"pt": "atualizável",
		"nl": "upgradebaar",
		"fr": "évolutif",
		"it": "aggiornabile",
		"es": "actualizable",
		"pl": "z możliwością aktualizacji",
		"zh-cn": "可升级的"
	},
	"packages": {
		"en": "packages",
		"de": "Pakete",
		"ru": "пакеты",
		"pt": "pacotes",
		"nl": "pakketjes",
		"fr": "paquets",
		"it": "pacchi",
		"es": "paquetes",
		"pl": "paczki",
		"zh-cn": "包装"
	},
	"newPackagesList": {
		"en": "new packages listed",
		"de": "neue Pakete aufgelistet",
		"ru": "новые пакеты в списке",
		"pt": "novos pacotes listados",
		"nl": "nieuwe pakketten vermeld",
		"fr": "nouveaux packages répertoriés",
		"it": "nuovi pacchetti elencati",
		"es": "nuevos paquetes listados",
		"pl": "wymienione nowe pakiety",
		"zh-cn": "列出了新包装"
	},
	"aptUpdate": {
		"en": "refresh packages lists",
		"de": "Paketlisten aktualisieren",
		"ru": "обновить списки пакетов",
		"pt": "atualizar listas de pacotes",
		"nl": "pakketlijsten vernieuwen",
		"fr": "actualiser les listes de packages",
		"it": "aggiorna gli elenchi dei pacchetti",
		"es": "actualizar listas de paquetes",
		"pl": "Odśwież listy pakietów",
		"zh-cn": "刷新软件包列表"
	},
	"aptUpgrade": {
		"en": "perform upgrade",
		"de": "Upgrade durchführen",
		"ru": "выполнить обновление",
		"pt": "realizar atualização",
		"nl": "upgrade uitvoeren",
		"fr": "effectuer une mise à niveau",
		"it": "eseguire l'aggiornamento",
		"es": "realizar actualización",
		"pl": "wykonać aktualizację",
		"zh-cn": "执行升级"
	},
	"controlResponse": {
		"en": "response of the executed command",
		"de": "Antwort des ausgeführten Befehls",
		"ru": "ответ выполненной команды",
		"pt": "resposta do comando executado",
		"nl": "reactie van het uitgevoerde commando",
		"fr": "réponse de la commande exécutée",
		"it": "risposta del comando eseguito",
		"es": "respuesta del comando ejecutado",
		"pl": "odpowiedź wykonanego polecenia",
		"zh-cn": "执行命令的响应"
	},
	"lastUpdate": {
		"en": "last update",
		"de": "letztes Update",
		"ru": "последнее обновление",
		"pt": "última atualização",
		"nl": "laatste update",
		"fr": "dernière mise à jour",
		"it": "ultimo aggiornamento",
		"es": "última actualización",
		"pl": "Ostatnia aktualizacja",
		"zh-cn": "最后更新"
	},
	"general": {
		"en": "general",
		"de": "Allgemein",
		"ru": "Общее",
		"pt": "geral",
		"nl": "algemeen",
		"fr": "général",
		"it": "generale",
		"es": "general",
		"pl": "generał",
		"zh-cn": "一般"
	},
	"datapoints": {
		"en": "datapoints",
		"de": "Datenpunkte",
		"ru": "точки данных",
		"pt": "Os pontos de dados",
		"nl": "data punten",
		"fr": "points de données",
		"it": "datapoints",
		"es": "puntos de datos",
		"pl": "punkty danych",
		"zh-cn": "数据点"
	},
	"expertsettings": {
		"en": "expert settings",
		"de": "Experteneinstellungen",
		"ru": "экспертные настройки",
		"pt": "configurações de especialistas",
		"nl": "deskundige instellingen",
		"fr": "réglages experts",
		"it": "impostazioni di esperti",
		"es": "ajustes expertos",
		"pl": "ustawienia ekspertów",
		"zh-cn": "专家设置"
	},
	"enableExpertSettings": {
		"en": "expert settings enable",
		"de": "Experteneinstellungen aktivieren",
		"ru": "экспертные настройки позволяют",
		"pt": "configurações especializadas permitem",
		"nl": "deskundige instellingen inschakelen",
		"fr": "les paramètres experts permettent",
		"it": "abilitazione impostazioni esperte",
		"es": "ajustes expertos habilitados",
		"pl": "włączenie ustawień eksperckich",
		"zh-cn": "专家设置启用"
	},
	"Host configuration table": {
		"en": "Host configuration table",
		"de": "Host Konfigurationstabelle",
		"ru": "Таблица конфигурации хоста",
		"pt": "Tabela de configuração do host",
		"nl": "Configuratietabel van host",
		"fr": "Table de configuration d'hôte",
		"it": "Tabella di configurazione dell'host",
		"es": "Tabla de configuración de host",
		"pl": "Tabela konfiguracji hosta",
		"zh-cn": "主机配置表"
	},
	"restart": {
		"en": "restart",
		"de": "neu starten",
		"ru": "запустить снова",
		"pt": "reiniciar",
		"nl": "herstarten",
		"fr": "redémarrer",
		"it": "ricomincia",
		"es": "reiniciar",
		"pl": "uruchom ponownie",
		"zh-cn": "重新开始"
	},
	"shutdown": {
		"en": "shutdown",
		"de": "Herunterfahren",
		"ru": "неисправность",
		"pt": "desligar",
		"nl": "afsluiten",
		"fr": "fermer",
		"it": "spegnimento",
		"es": "apagar",
		"pl": "zamknąć",
		"zh-cn": "关掉"
	},
	"whitelistServices": {
		"en": "only creating datapoints for the following services (empty to get all services)",
		"de": "Nur Datenpunkte für die folgenden Dienste erstellen (leer, um alle Dienste abzurufen)",
		"ru": "создание только точек данных для следующих сервисов (пусто для получения всех сервисов)",
		"pt": "apenas criando pontos de dados para os seguintes serviços (vazio para obter todos os serviços)",
		"nl": "alleen datapunten maken voor de volgende services (leeg om alle services te krijgen)",
		"fr": "création de points de données uniquement pour les services suivants (vide pour obtenir tous les services)",
		"it": "creando solo punti dati per i seguenti servizi (vuoto per ottenere tutti i servizi)",
		"es": "solo creando puntos de datos para los siguientes servicios (vacío para obtener todos los servicios)",
		"pl": "tylko tworzenie punktów danych dla następujących usług (puste, aby uzyskać wszystkie usługi)",
		"zh-cn": "仅为以下服务创建数据点（空获取所有服务）"
	},
	"root_control": {
		"en": "Remote control of your Linux distribution",
		"de": "Fernsteuerung deiner Linux-Distribution",
		"ru": "Удаленное управление вашим дистрибутивом Linux",
		"pt": "Controle remoto da sua distribuição Linux",
		"nl": "Afstandsbediening van uw Linux-distributie",
		"fr": "Contrôle à distance de votre distribution Linux",
		"it": "Controllo remoto della tua distribuzione Linux",
		"es": "Control remoto de su distribución de Linux",
		"pl": "Zdalna kontrola dystrybucji Linuksa",
		"zh-cn": "远程控制Linux发行版"
	},
	"root_distribution": {
		"en": "Information about your Linux distribution",
		"de": "Informationen über deine Linux-Distribution",
		"ru": "Информация о вашем дистрибутиве Linux",
		"pt": "Informações sobre sua distribuição Linux",
		"nl": "Informatie over uw Linux-distributie",
		"fr": "Informations sur votre distribution Linux",
		"it": "Informazioni sulla tua distribuzione Linux",
		"es": "Información sobre su distribución de Linux",
		"pl": "Informacje o twojej dystrybucji Linuksa",
		"zh-cn": "有关Linux发行版的信息"
	},
	"root_updates": {
		"en": "Information about updates",
		"de": "Informationen zu Updates",
		"ru": "Информация об обновлениях",
		"pt": "Informações sobre atualizações",
		"nl": "Informatie over updates",
		"fr": "Informations sur les mises à jour",
		"it": "Informazioni sugli aggiornamenti",
		"es": "Información sobre actualizaciones",
		"pl": "Informacje o aktualizacjach",
		"zh-cn": "有关更新的信息"
	},
	"root_services": {
		"en": "Information and remote control of services",
		"de": "Information und Fernsteuerung von Diensten",
		"ru": "Информационное и дистанционное управление услугами",
		"pt": "Informações e controle remoto de serviços",
		"nl": "Informatie en bediening op afstand van diensten",
		"fr": "Information et contrôle à distance des services",
		"it": "Informazioni e controllo remoto dei servizi",
		"es": "Información y control remoto de servicios.",
		"pl": "Informacje i zdalna kontrola usług",
		"zh-cn": "信息和服务的远程控制"
	},
	"root_needrestart": {
		"en": "Information if a reboot is necessary (package 'needrestart' must be installed)",
		"de": "Informationen ob ein Neustart erforderlich ist (Paket 'needrestart' muss installiert sein)",
		"ru": "Информация о необходимости перезагрузки (должен быть установлен пакет needrestart)",
		"pt": "Informações se uma reinicialização for necessária (o pacote 'needrestart' deve ser instalado)",
		"nl": "Informatie als een herstart nodig is (pakket 'needrestart' moet geïnstalleerd zijn)",
		"fr": "Information si un redémarrage est nécessaire (le package 'needrestart' doit être installé)",
		"it": "Informazioni se è necessario un riavvio (è necessario installare il pacchetto 'needrestart')",
		"es": "Información si es necesario reiniciar (se debe instalar el paquete 'needrestart')",
		"pl": "Informacja, czy konieczne jest ponowne uruchomienie komputera (należy zainstalować pakiet „needrestart”)",
		"zh-cn": "如果需要重新启动的信息（必须安装软件包“ needrestart”）"
	},
	"root_info": {
		"en": "infos about the host",
		"de": "Infos zum Host",
		"ru": "информация о хозяине",
		"pt": "informações sobre o anfitrião",
		"nl": "info over de gastheer",
		"fr": "infos sur l'hôte",
		"it": "informazioni sull'host",
		"es": "información sobre el anfitrión",
		"pl": "informacje o gospodarzu",
		"zh-cn": "有关主机的信息"
	},
	"is_online": {
		"en": "host is online",
		"de": "Host ist online",
		"ru": "хост в сети",
		"pt": "anfitrião está online",
		"nl": "gastheer is online",
		"fr": "l'hôte est en ligne",
		"it": "l'host è online",
		"es": "el anfitrión está en línea",
		"pl": "host jest online",
		"zh-cn": "主机在线"
	},
	"ip_address": {
		"en": "IP Address",
		"de": "IP Adresse",
		"ru": "Айпи адрес",
		"pt": "Endereço de IP",
		"nl": "IP adres",
		"fr": "Adresse IP",
		"it": "Indirizzo IP",
		"es": "Dirección IP",
		"pl": "Adres IP",
		"zh-cn": "IP地址"
	},
	"description": {
		"en": "description of service ",
		"de": "Beschreibung des Dienstes",
		"ru": "описание услуги",
		"pt": "Descrição do serviço",
		"nl": "beschrijving van de dienst",
		"fr": "description du service",
		"it": "descrizione del servizio",
		"es": "descripción del Servicio",
		"pl": "opis usługi",
		"zh-cn": "服务说明"
	},
	"load": {
		"en": "service loaded",
		"de": "Dienst geladen",
		"ru": "сервис загружен",
		"pt": "serviço carregado",
		"nl": "service geladen",
		"fr": "service chargé",
		"it": "servizio caricato",
		"es": "servicio cargado",
		"pl": "usługa załadowana",
		"zh-cn": "服务加载"
	},
	"active": {
		"en": "service active",
		"de": "Dienst aktiv",
		"ru": "служба активна",
		"pt": "serviço ativo",
		"nl": "dienst actief",
		"fr": "service actif",
		"it": "servizio attivo",
		"es": "servicio activo",
		"pl": "usługa aktywna",
		"zh-cn": "服务活跃"
	},
	"running": {
		"en": "service running",
		"de": "Dienst läuft",
		"ru": "служба работает",
		"pt": "serviço em execução",
		"nl": "service loopt",
		"fr": "service en cours d'exécution",
		"it": "servizio in esecuzione",
		"es": "servicio en ejecución",
		"pl": "usługa działa",
		"zh-cn": "服务运行"
	},
	"restartService": {
		"en": "restart service ",
		"de": "Dienst neu starten",
		"ru": "перезапустить службу",
		"pt": "reiniciar o serviço",
		"nl": "herstart service",
		"fr": "redémarrer le service",
		"it": "riavvia il servizio",
		"es": "reiniciar servicio",
		"pl": "uruchom ponownie usługę",
		"zh-cn": "重新启动服务"
	},
	"stopService": {
		"en": "stop service ",
		"de": "Dienst anhalten",
		"ru": "остановить сервис",
		"pt": "parar serviço",
		"nl": "stop service",
		"fr": "aire d'autoroute",
		"it": "interrompere il servizio",
		"es": "parada de servicio",
		"pl": "zatrzymać usługę",
		"zh-cn": "停止服务"
	},
	"startService": {
		"en": "start service ",
		"de": "Dienst starten",
		"ru": "начать обслуживание",
		"pt": "Começar serviço",
		"nl": "start dienst",
		"fr": "démarrer le service",
		"it": "avviare il servizio",
		"es": "Empieza el servicio",
		"pl": "uruchomić usługę",
		"zh-cn": "开始服务"
	},
	"needrestart": {
		"en": "restart is needed",
		"de": "Neustart ist erforderlich",
		"ru": "требуется перезагрузка",
		"pt": "é necessário reiniciar",
		"nl": "herstart is nodig",
		"fr": "le redémarrage est nécessaire",
		"it": "è necessario il riavvio",
		"es": "reiniciar es necesario",
		"pl": "konieczne jest ponowne uruchomienie",
		"zh-cn": "需要重启"
	},
	"needRestartServices": {
		"en": "count of services that need a restart",
		"de": "Anzahl der Dienste, die neu gestartet werden müssen",
		"ru": "количество служб, требующих перезапуска",
		"pt": "contagem de serviços que precisam de reinicialização",
		"nl": "aantal services dat opnieuw moet worden opgestart",
		"fr": "nombre de services nécessitant un redémarrage",
		"it": "conteggio dei servizi che richiedono un riavvio",
		"es": "recuento de servicios que necesitan reiniciar",
		"pl": "liczba usług wymagających ponownego uruchomienia",
		"zh-cn": "需要重启的服务数量"
	},
	"needRestartContainers": {
		"en": "count of containers that need a restart",
		"de": "Anzahl der Container, die neu gestartet werden müssen",
		"ru": "количество контейнеров, которые требуют перезагрузки",
		"pt": "contagem de contêineres que precisam de reinicialização",
		"nl": "aantal containers dat opnieuw moet worden opgestart",
		"fr": "nombre de conteneurs nécessitant un redémarrage",
		"it": "conteggio dei contenitori che richiedono un riavvio",
		"es": "recuento de contenedores que necesitan reiniciar",
		"pl": "liczba kontenerów wymagających ponownego uruchomienia",
		"zh-cn": "需要重启的容器数量"
	},
	"needRestartSessions": {
		"en": "count of sessions that need a restart",
		"de": "Anzahl der Sitzungen, die neu gestartet werden müssen",
		"ru": "количество сеансов, требующих перезапуска",
		"pt": "contagem de sessões que precisam ser reiniciadas",
		"nl": "aantal sessies dat opnieuw moet worden opgestart",
		"fr": "nombre de sessions nécessitant un redémarrage",
		"it": "conteggio delle sessioni che richiedono un riavvio",
		"es": "recuento de sesiones que necesitan reiniciar",
		"pl": "liczba sesji wymagających ponownego uruchomienia",
		"zh-cn": "需要重启的会话数"
	},
	"AddService": {
		"en": "add service",
		"de": "Dienst hinzufügen",
		"ru": "добавить сервис",
		"pt": "adicionar serviço",
		"nl": "service toevoegen",
		"fr": "ajouter un service",
		"it": "aggiungi servizio",
		"es": "agregar servicio",
		"pl": "dodaj usługę",
		"zh-cn": "添加服务"
	},
	"Table to configure folders to display their size as data points": {
		"en": "Table to configure folders to display their size as data points",
		"de": "Tabelle zum Konfigurieren von Ordnern, um deren Größe als Datenpunkte anzuzeigen",
		"ru": "Таблица для настройки папок для отображения их размера в виде точек данных",
		"pt": "Tabela para configurar pastas para exibir seu tamanho como pontos de dados",
		"nl": "Tabel om mappen te configureren om hun grootte als gegevenspunten weer te geven",
		"fr": "Tableau pour configurer les dossiers pour afficher leur taille en tant que points de données",
		"it": "Tabella per configurare le cartelle in modo da visualizzarne le dimensioni come punti dati",
		"es": "Tabla para configurar carpetas para mostrar su tamaño como puntos de datos",
		"pl": "Tabela konfiguracji folderów w celu wyświetlania ich rozmiaru jako punktów danych",
		"zh-cn": "用于配置文件夹以将其大小显示为数据点的表"
	},
	"folderSize": {
		"en": "size of folder",
		"de": "Größe des Ordners",
		"ru": "размер папки",
		"pt": "tamanho da pasta",
		"nl": "grootte van de map",
		"fr": "taille du dossier",
		"it": "dimensione della cartella",
		"es": "tamaño de carpeta",
		"pl": "rozmiar folderu",
		"zh-cn": "资料夹大小"
	},
	"Digits": {
		"en": "decimal places",
		"de": "Komma-stellen",
		"ru": "десятичные знаки",
		"pt": "casas decimais",
		"nl": "decimalen",
		"fr": "décimales",
		"it": "decimali",
		"es": "lugares decimales",
		"pl": "miejsca dziesiętne",
		"zh-cn": "小数位"
	},
	"Path": {
		"en": "Path",
		"de": "Pfad",
		"ru": "Дорожка",
		"pt": "Caminho",
		"nl": "Pad",
		"fr": "Chemin",
		"it": "Sentiero",
		"es": "Camino",
		"pl": "Ścieżka",
		"zh-cn": "路径"
	},
	"Unit": {
		"en": "Unit",
		"de": "Einheit",
		"ru": "Единица измерения",
		"pt": "Unidade",
		"nl": "Eenheid",
		"fr": "Unité",
		"it": "Unità",
		"es": "Unidad",
		"pl": "Jednostka",
		"zh-cn": "单元"
	},
	"folders": {
		"en": "folders",
		"de": "Ordner",
		"ru": "папки",
		"pt": "pastas",
		"nl": "mappen",
		"fr": "Dossiers",
		"it": "cartelle",
		"es": "carpetas",
		"pl": "lornetka składana",
		"zh-cn": "资料夹"
	},
	"timeout": {
		"en": "timeout",
		"de": "Timeout",
		"ru": "Тайм-аут",
		"pt": "tempo esgotado",
		"nl": "time-out",
		"fr": "temps libre",
		"it": "tempo scaduto",
		"es": "se acabó el tiempo",
		"pl": "koniec czasu",
		"zh-cn": "超时"
	},
	"Table to configure your own commands": {
		"en": "Table to configure your own commands",
		"de": "Tabelle zum Konfigurieren deiner eigenen Befehle",
		"ru": "Таблица для настройки ваших собственных команд",
		"pt": "Tabela para configurar seus próprios comandos",
		"nl": "Tabel om uw eigen commando's te configureren",
		"fr": "Tableau pour configurer vos propres commandes",
		"it": "Tabella per configurare i tuoi comandi",
		"es": "Tabla para configurar tus propios comandos",
		"pl": "Tabela do konfiguracji własnych poleceń",
		"zh-cn": "该表配置您自己的命令"
	},
	"mycommands": {
		"en": "my commands",
		"de": "meine Befehle",
		"ru": "мои команды",
		"pt": "meus comandos",
		"nl": "mijn bevelen",
		"fr": "mes commandes",
		"it": "i miei comandi",
		"es": "mis comandos",
		"pl": "moje polecenia",
		"zh-cn": "我的命令"
	},
	"Command": {
		"en": "Command",
		"de": "Befehl",
		"ru": "команда",
		"pt": "Comando",
		"nl": "Commando",
		"fr": "Commander",
		"it": "Comando",
		"es": "Mando",
		"pl": "Komenda",
		"zh-cn": "命令"
	},
	"string": {
		"en": "string",
		"de": "Zeichenkette",
		"ru": "строка",
		"pt": "corda",
		"nl": "draad",
		"fr": "chaîne",
		"it": "corda",
		"es": "cuerda",
		"pl": "strunowy",
		"zh-cn": "串"
	},
	"number": {
		"en": "number",
		"de": "Zahl",
		"ru": "число",
		"pt": "número",
		"nl": "aantal",
		"fr": "nombre",
		"it": "numero",
		"es": "número",
		"pl": "numer",
		"zh-cn": "数"
	},
	"boolean": {
		"en": "boolean",
		"de": "Logikwert",
		"ru": "логический",
		"pt": "boleano",
		"nl": "boolean",
		"fr": "booléen",
		"it": "booleano",
		"es": "booleano",
		"pl": "boolean",
		"zh-cn": "布尔值"
	},
	"array": {
		"en": "array",
		"de": "Array",
		"ru": "массив",
		"pt": "matriz",
		"nl": "matrix",
		"fr": "tableau",
		"it": "Vettore",
		"es": "formación",
		"pl": "szyk",
		"zh-cn": "数组"
	},
	"button": {
		"en": "button",
		"de": "Button",
		"ru": "кнопка",
		"pt": "botão",
		"nl": "knop",
		"fr": "bouton",
		"it": "pulsante",
		"es": "botón",
		"pl": "przycisk",
		"zh-cn": "纽扣"
	},
	"Type": {
		"en": "Type",
		"de": "Typ",
		"ru": "Тип",
		"pt": "Tipo",
		"nl": "Type",
		"fr": "Type",
		"it": "genere",
		"es": "Tipo",
		"pl": "Rodzaj",
		"zh-cn": "类型"
	},
	"donation": {
		"en": "You like the adapter? Then support the adapter developer (Scrounger) with a small donation.",
		"de": "Dir gefällt der Adapter? Dann unterstütze den Adapterentwickler (Scrounger) mit einer kleinen Spende.",
		"ru": "Вам нравится адаптер? Затем поддержите разработчика адаптера (Scrounger) с небольшим пожертвованием.",
		"pt": "Você gosta do adaptador? Depois, ofereça suporte ao desenvolvedor do adaptador (Scrounger) com uma pequena doação.",
		"nl": "Vind je de adapter leuk? Ondersteun vervolgens de adapterontwikkelaar (Scrounger) met een kleine donatie.",
		"fr": "Vous aimez l'adaptateur? Soutenez ensuite le développeur de l'adaptateur (Scrounger) avec un petit don.",
		"it": "Ti piace l'adattatore? Quindi supportare lo sviluppatore dell'adattatore (Scrounger) con una piccola donazione.",
		"es": "¿Te gusta el adaptador? Luego, apoye al desarrollador del adaptador (Scrounger) con una pequeña donación.",
		"pl": "Podoba ci się adapter? Następnie wesprzyj programistę adaptera (Scrounger) niewielką darowizną.",
		"zh-cn": "您喜欢适配器吗？然后以少量捐款支持适配器开发人员（Scrounger）。"
	},
	"pollingInterval_seconds": {
		"en": "polling interval (seconds)",
		"de": "Abfrageintervall (Sekunden)",
		"ru": "интервал опроса (секунды)",
		"pt": "intervalo de sondagem (segundos)",
		"nl": "polling-interval (seconden)",
		"fr": "intervalle d'interrogation (secondes)",
		"it": "intervallo di polling (secondi)",
		"es": "intervalo de sondeo (segundos)",
		"pl": "okres odpytywania (w sekundach)",
		"zh-cn": "轮询间隔（秒）"
	},
	"use Sudo": {
		"en": "use Sudo",
		"de": "benutze Sudo",
		"ru": "использовать судо",
		"pt": "use Sudo",
		"nl": "gebruik Sudo",
		"fr": "utiliser Sudo",
		"it": "usa il Sudo",
		"es": "usar sudo",
		"pl": "użyj Sudo",
		"zh-cn": "使用须藤"
	},
	"enabled": {
		"en": "enabled",
		"de": "aktiviert",
		"ru": "включен",
		"pt": "ativado",
		"nl": "ingeschakeld",
		"fr": "activée",
		"it": "abilitato",
		"es": "habilitado",
		"pl": "włączone",
		"zh-cn": "已启用"
	},
	"countFiles": {
		"en": "count of files",
		"de": "Anzahl Dateien",
		"ru": "количество файлов",
		"pt": "contagem de arquivos",
		"nl": "aantal bestanden",
		"fr": "nombre de fichiers",
		"it": "conteggio dei file",
		"es": "recuento de archivos",
		"pl": "liczba plików",
		"zh-cn": "文件数"
	},
	"lastChange": {
		"en": "last change",
		"de": "letzte Änderung",
		"ru": "последнее изменение",
		"pt": "última mudança",
		"nl": "laatste wijziging",
		"fr": "dernier changement",
		"it": "ultima modifica",
		"es": "ultimo cambio",
		"pl": "Ostatnia zmiana",
		"zh-cn": "最后一次变更"
	},
	"countFilesInFolder": {
		"en": "count of files in folder",
		"de": "Anzahl der Dateien im Ordner",
		"ru": "количество файлов в папке",
		"pt": "contagem de arquivos na pasta",
		"nl": "aantal bestanden in de map",
		"fr": "nombre de fichiers dans le dossier",
		"it": "conteggio dei file nella cartella",
		"es": "recuento de archivos en carpeta",
		"pl": "liczba plików w folderze",
		"zh-cn": "文件夹中文件的数量"
	},
	"files": {
		"en": "files",
		"de": "Dateien",
		"ru": "файлы",
		"pt": "arquivos",
		"nl": "bestanden",
		"fr": "des dossiers",
		"it": "File",
		"es": "archivos",
		"pl": "pliki",
		"zh-cn": "档案"
	},
	"fileNamePattern": {
		"en": "file name pattern",
		"de": "Dateinamen Muster",
		"ru": "шаблон имени файла",
		"pt": "padrão de nome de arquivo",
		"nl": "bestandsnaampatroon",
		"fr": "modèle de nom de fichier",
		"it": "modello di nome file",
		"es": "patrón de nombre de archivo",
		"pl": "wzorzec nazwy pliku",
		"zh-cn": "文件名模式"
	},
	"last change": {
		"en": "last change",
		"de": "letzte Änderung",
		"ru": "последнее изменение",
		"pt": "última mudança",
		"nl": "laatste wijziging",
		"fr": "dernier changement",
		"it": "ultima modifica",
		"es": "ultimo cambio",
		"pl": "Ostatnia zmiana",
		"zh-cn": "最后一次变更"
	},
	"refreshHost": {
		"en": "refresh host",
		"de": "Host aktualisieren",
		"ru": "обновить хост",
		"pt": "atualizar host",
		"nl": "vernieuw de host",
		"fr": "rafraîchir l'hôte",
		"it": "aggiorna host",
		"es": "actualizar host",
		"pl": "odśwież hosta",
		"zh-cn": "刷新主机"
	},
	"lastRefresh": {
		"en": "last refresh of host",
		"de": "letzte Aktualisierung des Hosts",
		"ru": "последнее обновление хоста",
		"pt": "última atualização do host",
		"nl": "laatste vernieuwing van host",
		"fr": "dernier rafraîchissement de l'hôte",
		"it": "ultimo aggiornamento dell'host",
		"es": "última actualización del host",
		"pl": "ostatnie odświeżenie hosta",
		"zh-cn": "主机的最新刷新"
	},
	"lc_settings": {
		"en": "adapter settings",
		"de": "Adaptereinstellungen",
		"ru": "настройки адаптера",
		"pt": "configurações do adaptador",
		"nl": "adapter instellingen",
		"fr": "paramètres de l'adaptateur",
		"it": "impostazioni dell'adattatore",
		"es": "configuración del adaptador",
		"pl": "ustawienia adaptera",
		"zh-cn": "适配器设置"
	},
	"lc_forum": {
		"en": "forum",
		"de": "Forum",
		"ru": "Форум",
		"pt": "fórum",
		"nl": "forum",
		"fr": "forum",
		"it": "Forum",
		"es": "foro",
		"pl": "forum",
		"zh-cn": "论坛"
	},
	"blacklistDatapoints": {
		"en": "excluded datapoints ",
		"de": "ausgeschlossene Datenpunkte",
		"ru": "исключенные точки данных",
		"pt": "pontos de dados excluídos",
		"nl": "uitgesloten datapunten",
		"fr": "points de données exclus",
		"it": "datapoint esclusi",
		"es": "puntos de datos excluidos",
		"pl": "wykluczone punkty danych",
		"zh-cn": "排除的数据点"
	},
	"WhitelistServices": {
		"en": "create datapoints for",
		"de": "Datenpunkte erstellen für",
		"ru": "создать точки данных для",
		"pt": "criar pontos de dados para",
		"nl": "maak datapunten voor",
		"fr": "créer des points de données pour",
		"it": "creare datapoint per",
		"es": "crear puntos de datos para",
		"pl": "utwórz punkty danych dla",
		"zh-cn": "为创建数据点"
	},
	"add_host": {
		"en": "add host",
		"de": "Host hinzufügen",
		"ru": "добавить хост",
		"pt": "adicionar hospedeiro",
		"nl": "host toevoegen",
		"fr": "ajouter un hôte",
		"it": "aggiungi host",
		"es": "agregar anfitrión",
		"pl": "dodaj hosta",
		"zh-cn": "添加主机"
	},
	"add_command": {
		"en": "add command",
		"de": "Befehl hinzufügen",
		"ru": "добавить команду",
		"pt": "adicionar comando",
		"nl": "add commando",
		"fr": "ajouter une commande",
		"it": "aggiungi comando",
		"es": "agregar comando",
		"pl": "dodaj polecenie",
		"zh-cn": "添加命令"
	},
	"add_folder": {
		"en": "add folder",
		"de": "Ordner hinzufügen",
		"ru": "добавить папку",
		"pt": "adicionar pasta",
		"nl": "map toevoegen",
		"fr": "ajouter le dossier",
		"it": "Aggiungi cartella",
		"es": "agregar carpeta",
		"pl": "Dodaj folder",
		"zh-cn": "新增文件夹"
	},
	"globalSettings": {
		"en": "Global settings",
		"de": "Globale Einstellungen",
		"ru": "Глобальные настройки",
		"pt": "Configurações globais",
		"nl": "Global setting",
		"fr": "Paramètres mondiaux",
		"it": "Impostazioni globali",
		"es": "Ajustes globales",
		"pl": "Globalna ustawa",
		"zh-cn": "B. 全球环境"
	},
	"aptUpdateInterval": {
		"en": "Get information about updates only every x minutes (0 = use host interval)",
		"de": "Informationen zu Updates nur alle x Minuten abrufen (0 = Host-Intervall)",
		"ru": "Получать информацию об обновлениях только каждые x минуты (0 = использовать интервал хоста)",
		"pt": "Obtenha informações sobre atualizações apenas a cada minuto x (0 = use intervalo de host)",
		"nl": "Zorg voor informatie over updates maar elke X minuten",
		"fr": "Obtenez des informations sur les mises à jour seulement toutes les x minutes (0 = intervalle d'utilisation)",
		"it": "Ottenere informazioni sugli aggiornamenti solo ogni x minuti (0 = utilizzare l'intervallo host)",
		"es": "Obtenga información sobre las actualizaciones sólo cada x minutos (0 = uso intervalo de host)",
		"pl": "Dane na temat aktualizacji są dostępne tylko w każdej x minuty (0 = 0)",
		"zh-cn": "仅提供每十分钟(0 = 使用东道国间汇率)的最新情况"
	}
};

try {
	// @ts-ignore
	systemDictionary = dictionary;
} catch (ignore) { }

try {
	module.exports = dictionary;
} catch (ignore) { }